### ISSUE TITLE
Error creating temp folder.

### ISSUE THREAD

**Issue by random-robbie** [deepfence/SecretScanner#26]
```
root@bb1:~# SecretScanner -image-name worker1
Initializing....
Scanning image worker1 for secrets...
scanImage: Could save container image failed to save image: invalid output path: directory "/tmp/Deepfence/SecretScanning/df_worker1" does not exist

findSecretsInImage: failed to save image: invalid output path: directory "/tmp/Deepfence/SecretScanning/df_worker1" does not exist

main: error while scanning image: failed to save image: invalid output path: directory "/tmp/Deepfence/SecretScanning/df_worker1" does not exist

panic: Fatal error....

goroutine 1 [running]:
github.com/deepfence/SecretScanner/core.(*Logger).Log(0x7ffc1c756662, 0x5, {0x56cb7e, 0x24}, {0xc00033ff50, 0x1, 0x1})
	/root/go/src/github.com/deepfence/SecretScanner/core/log.go:68 +0x25e
github.com/deepfence/SecretScanner/core.(*Logger).Fatal(...)
	/root/go/src/github.com/deepfence/SecretScanner/core/log.go:73
main.main()
	/root/go/src/github.com/deepfence/SecretScanner/main.go:139 +0x14c
```

Ubuntu 20
go version go1.17.6 linux/amd64

**Comment by random-robbie** [comment]
Despite running as root i had to supply -temp-folder /root/tmp/ and it worked.
